name: Python Tests

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8 src tests
      - name: Run mypy
        run: mypy src
      - name: Run unit tests
        run: python tests/run_tests.py -k "not test_public_functions_are_decorated and not test_notebook"
      - name: Run notebook tests
        run: python tests/run_tests.py tests/test_notebooks.py -v
